title: <p align="left"> Antony John Sundar </p>
logo: /assets/img/ProfilePhoto.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/ajscbe/">LinkedIn</a> |
  <a href="https://github.com/AntonyJohnSundar/">GitHub</a>
  <br>  
  I am working as a QA Delivery Manager at Fintech company.
  I am an AI and ML enthusiast , pursuing a Master's degree in AI and ML.
  <br>
  </p>
#show_downloads: true









theme: jekyll-theme-minimal

